# Generated by Django 6.0.3 on 2026-04-26 20:19

import django.db.models.deletion
import employee_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_remove_team_department_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktask',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('Done', 'Done'), ('Blocked', 'Blocked')], default='To Do', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkTaskLog',
            fields=[
                ('logID', models.CharField(default=employee_management.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='employee_management.worktask')),
            ],
            options={
                'db_table': 'WorkTaskLog',
                'ordering': ['-start_time'],
            },
        ),
    ]
