# Generated by Django 6.0.3 on 2026-04-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_remove_employee_age_remove_employee_yearsatcompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Senior', 'Senior')], max_length=100, null=True),
        ),
    ]
