# Generated by Django 6.0.3 on 2026-04-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_alter_job_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='numberOfPromotions',
        ),
    ]
