# Generated by Django 6.0.3 on 2026-05-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_remove_employee_numberofpromotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
