# Generated by Django 6.0.3 on 2026-05-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0007_alter_job_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='actualHours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
