# Generated by Django 6.0.3 on 2026-06-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0009_employee_contracted_hours_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='approvedAmount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='HR-approved amount (may differ from the claimed amount).', max_digits=10, null=True),
        ),
    ]
