# Generated by Django 6.0.3 on 2026-06-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0010_expenseclaim_approvedamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='reviewNote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='worktask',
            name='reviewedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
