# Generated by Django 6.0.3 on 2026-06-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0011_worktask_reviewnote_worktask_reviewedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leaving_date',
            field=models.DateField(blank=True, help_text='Last day of employment; used to clip the payroll proration window for mid-month leavers.', null=True),
        ),
    ]
