# Generated by Django 6.0.3 on 2026-06-10 14:59

import django.db.models.deletion
import employee_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0012_employee_leaving_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('messageID', models.CharField(default=employee_management.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('authorRole', models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin')], max_length=20)),
                ('authorName', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField()),
                ('isResolution', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(db_column='ticketID', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='employee_management.supportticket')),
            ],
            options={
                'db_table': 'SupportTicketMessage',
                'ordering': ['createdAt'],
            },
        ),
    ]
