# Generated by Django 6.0.3 on 2026-06-15 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0015_leavetype_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, help_text="The team's leader (an employee with the TeamLeader role).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='employee_management.employee'),
        ),
    ]
