# Generated by Django 6.0.3 on 2026-06-10 16:39

import Attendance_and_Leave.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_and_Leave', '0003_attendancerecord_overtime_review'),
        ('employee_management', '0013_supportticketmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCorrectionRequest',
            fields=[
                ('correctionID', models.CharField(default=Attendance_and_Leave.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('requestedClockIn', models.DateTimeField(blank=True, null=True)),
                ('requestedClockOut', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20)),
                ('reviewNote', models.TextField(blank=True)),
                ('reviewedBy', models.CharField(blank=True, max_length=150)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(db_column='attendanceID', on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='Attendance_and_Leave.attendancerecord')),
                ('employee', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='time_correction_requests', to='employee_management.employee')),
            ],
            options={
                'db_table': 'TimeCorrectionRequest',
                'ordering': ['-createdAt'],
            },
        ),
    ]
