# Generated by Django 6.0.3 on 2026-06-11 21:18

import Attendance_and_Leave.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_and_Leave', '0004_timecorrectionrequest'),
        ('employee_management', '0013_supportticketmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayOverride',
            fields=[
                ('overrideID', models.CharField(default=Attendance_and_Leave.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], default='add', max_length=10)),
                ('createdBy', models.CharField(blank=True, max_length=150)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'HolidayOverride',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('balanceID', models.CharField(default=Attendance_and_Leave.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('leaveTypeName', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('entitledDays', models.PositiveIntegerField(blank=True, help_text='Max days for the year; None = uncapped (Unpaid).', null=True)),
                ('usedDays', models.PositiveIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employee_management.employee')),
                ('leaveType', models.ForeignKey(blank=True, db_column='leave_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_balances', to='employee_management.leavetype')),
            ],
            options={
                'db_table': 'LeaveBalance',
                'ordering': ['-year', 'leaveTypeName'],
                'unique_together': {('employee', 'leaveTypeName', 'year')},
            },
        ),
    ]
