# Generated by Django 6.0.3 on 2026-06-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_and_Leave', '0006_leaverequest_leavetype_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='document',
            field=models.FileField(blank=True, help_text='Optional supporting document (e.g. medical note).', null=True, upload_to='leave_documents/'),
        ),
    ]
