# Generated by Django 6.0.3 on 2026-04-20 14:09

import django.db.models.deletion
import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0024_delete_onboardingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingPlan',
            fields=[
                ('planID', models.CharField(default=onboarding.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('planType', models.CharField(choices=[('Onboarding', 'Onboarding'), ('Offboarding', 'Offboarding'), ('Transition', 'Transition')], default='Onboarding', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Blocked', 'Blocked')], default='Not Started', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('targetDate', models.DateField(blank=True, null=True)),
                ('checklistItems', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('employeeNote', models.TextField(blank=True)),
                ('createdBy', models.CharField(blank=True, max_length=150)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_plans', to='feedback.employee')),
            ],
            options={
                'db_table': 'OnboardingPlan',
                'ordering': ['targetDate', '-createdAt'],
            },
        ),
    ]
