# Generated by Django 6.0.3 on 2026-06-04 17:02

import django.db.models.deletion
import payroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0012_employee_leaving_date'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='commissions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of manual HR commission entries for this employee + pay period.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='dailyRate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Base salary / total weekdays in the month.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='expenseReimbursements',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of approvedAmount for HR-approved expense claims in the pay period.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='proratedBaseSalary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base salary after mid-month join/leave proration; used in net pay.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='unpaidLeaveDays',
            field=models.PositiveIntegerField(default=0, help_text='Counted unpaid-leave weekdays within the employment window.'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='unpaidLeaveDeduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daily rate × counted unpaid-leave weekdays within the employment window.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='weekdaysEmployed',
            field=models.PositiveIntegerField(default=0, help_text='Weekdays in the month falling within the employment window.'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='workingDays',
            field=models.PositiveIntegerField(default=0, help_text='Weekdays (Mon-Fri) in the pay-period month.'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='baseSalary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Full contractual monthly base salary (before proration).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manual HR-entered deductions (excludes unpaid-leave deduction).', max_digits=10),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('commissionID', models.CharField(default=payroll.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('payPeriod', models.CharField(help_text="Pay period in 'YYYY-MM' format.", max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('createdBy', models.CharField(blank=True, max_length=150)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='employee_management.employee')),
            ],
            options={
                'db_table': 'Commission',
                'ordering': ['-payPeriod', '-createdAt'],
            },
        ),
    ]
