# Generated by Django 6.0.3 on 2026-06-04 17:15

import django.db.models.deletion
import payroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0012_employee_leaving_date'),
        ('payroll', '0002_payrollrecord_commissions_payrollrecord_dailyrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='description',
            field=models.CharField(blank=True, help_text='HR note explaining why this commission was awarded.', max_length=255),
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('deductionID', models.CharField(default=payroll.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('payPeriod', models.CharField(help_text="Pay period in 'YYYY-MM' format.", max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, help_text='HR note explaining why this deduction was applied.', max_length=255)),
                ('createdBy', models.CharField(blank=True, max_length=150)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='manual_deductions', to='employee_management.employee')),
            ],
            options={
                'db_table': 'Deduction',
                'ordering': ['-payPeriod', '-createdAt'],
            },
        ),
    ]
