# Generated by Django 6.0.3 on 2026-06-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_commission_description_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='hourlyRate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Regular hourly rate = daily rate / contracted hours per day.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='overtimeHours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Approved overtime hours in the pay period.', max_digits=8),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='overtimePay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime pay = approved overtime hours × hourly rate × 1.5.', max_digits=10),
        ),
    ]
