# Generated by Django 6.0.3 on 2026-06-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollrecord_hourlyrate_payrollrecord_overtimehours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='createdBy',
            field=models.CharField(blank=True, help_text='Who generated this payroll record.', max_length=150),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='editReason',
            field=models.TextField(blank=True, help_text='Note explaining the most recent manual edit.'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='editedAt',
            field=models.DateTimeField(blank=True, help_text='When an HR user last manually edited this record.', null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='editedBy',
            field=models.CharField(blank=True, help_text='Who last manually edited this record.', max_length=150),
        ),
    ]
