# Generated by Django 6.0.3 on 2026-04-23 22:45

import django.db.models.deletion
import resume_pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Full job description text')),
                ('required_skills', models.JSONField(default=list)),
                ('min_experience_years', models.FloatField(default=0)),
                ('required_degree', models.CharField(default='Unknown', max_length=20)),
                ('weight_skills', models.FloatField(default=0.4)),
                ('weight_experience', models.FloatField(default=0.3)),
                ('weight_education', models.FloatField(default=0.1)),
                ('weight_semantic', models.FloatField(default=0.2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=255)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('tracking_code', models.CharField(default=resume_pipeline.models.generate_tracking_code, editable=False, max_length=16, unique=True)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('review_stage', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
                ('stage_notes', models.TextField(blank=True)),
                ('stage_updated_at', models.DateTimeField(blank=True, null=True)),
                ('talent_pool', models.BooleanField(default=True)),
                ('stage_history', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('raw_text', models.TextField(blank=True)),
                ('candidate_skills', models.JSONField(default=list)),
                ('candidate_degree', models.CharField(default='Unknown', max_length=20)),
                ('candidate_years_exp', models.FloatField(default=0.0)),
                ('exp_extraction_method', models.CharField(blank=True, max_length=50)),
                ('skills_score', models.FloatField(null=True)),
                ('experience_score', models.FloatField(null=True)),
                ('education_score', models.FloatField(null=True)),
                ('semantic_score', models.FloatField(null=True)),
                ('ats_score', models.FloatField(null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='resume_pipeline.job')),
            ],
            options={
                'ordering': ['-ats_score'],
            },
        ),
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('planID', models.CharField(default=resume_pipeline.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('targetRole', models.CharField(max_length=120)),
                ('readiness', models.CharField(choices=[('Ready Now', 'Ready Now'), ('6-12 Months', '6-12 Months'), ('1-2 Years', '1-2 Years'), ('Long Term', 'Long Term')], default='1-2 Years', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Track', 'On Track'), ('Acknowledged', 'Acknowledged'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Active', max_length=20)),
                ('retentionRisk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('developmentActions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('employeeNote', models.TextField(blank=True)),
                ('acknowledgedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=150)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='succession_plans', to='employee_management.employee')),
            ],
            options={
                'db_table': 'SuccessionPlan',
                'ordering': ['-updatedAt', '-createdAt'],
            },
        ),
    ]
