# Generated by Django 6.0.3 on 2026-05-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='level',
            field=models.CharField(blank=True, help_text='Must match an employee_management.Job (title, level) pair.', max_length=100, null=True),
        ),
    ]
