# Generated by Django 6.0.3 on 2026-05-30 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_pipeline', '0002_job_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='interviewer',
            field=models.ForeignKey(blank=True, help_text='HR Manager or Team Leader responsible for interviewing candidates for this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewing_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.PositiveIntegerField(default=1, help_text='Number of target hires for this posting.'),
        ),
    ]
