# Generated by Django 6.0.3 on 2026-05-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_pipeline', '0003_job_interviewer_job_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pipeline_stages',
            field=models.JSONField(blank=True, default=list, help_text="Ordered list of HR-defined hiring stages. Empty falls back to the system default. 'Rejected' is implicit and never stored here."),
        ),
        migrations.AlterField(
            model_name='submission',
            name='review_stage',
            field=models.CharField(default='Applied', max_length=50),
        ),
    ]
