# Generated by Django 6.0.3 on 2026-04-23 22:45

import django.db.models.deletion
import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('employeeID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'feedback_admin',
            },
        ),
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('formID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdByAdminID', models.ForeignKey(blank=True, db_column='createdByAdminID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to='feedback.adminuser')),
            ],
            options={
                'db_table': 'FeedbackForm',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('questionID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('questionText', models.CharField(max_length=300)),
                ('fieldType', models.CharField(choices=[('score_1_4', 'Score 1-4'), ('boolean', 'Yes / No'), ('decimal', 'Decimal Number')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('formID', models.ForeignKey(db_column='formID', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='feedback.feedbackform')),
            ],
            options={
                'db_table': 'FeedbackQuestion',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('submissionID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('submittedAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('employeeID', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='employee_management.employee')),
                ('formID', models.ForeignKey(db_column='formID', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='feedback.feedbackform')),
            ],
            options={
                'db_table': 'FeedbackSubmission',
                'unique_together': {('formID', 'employeeID')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('answerID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('scoreValue', models.IntegerField(blank=True, null=True)),
                ('booleanValue', models.BooleanField(blank=True, null=True)),
                ('decimalValue', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('questionID', models.ForeignKey(db_column='questionID', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.feedbackquestion')),
                ('submissionID', models.ForeignKey(db_column='submissionID', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.feedbacksubmission')),
            ],
            options={
                'db_table': 'FeedbackAnswer',
                'unique_together': {('submissionID', 'questionID')},
            },
        ),
    ]
