# Generated by Django 6.0.3 on 2026-04-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0023_employee_currency_preference_payrollrecord_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnboardingPlan',
        ),
    ]
